# Generated by Django 4.2.3 on 2023-07-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controllers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('access_mode', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('refresh_rate', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('last_accessed_at', models.CharField(max_length=100)),
                ('external_id', models.CharField(max_length=100)),
                ('created_at', models.CharField(max_length=100)),
                ('institution_user_id', models.CharField(max_length=255)),
                ('credentials_storage', models.CharField(max_length=100)),
                ('fetch_historical', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClientData',
        ),
    ]
