# Generated by Django 4.2.3 on 2023-07-26 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_controllers', '0002_linksdata_delete_clientdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksdata',
            name='user',
            field=models.ForeignKey(default='123456789', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='criado pelo usuário:'),
        ),
    ]
